name: ROS2 Kart Racing Competition
author: George Stavrinos
description: The action that is used by the ros2_kart_racing competition package to add users to the leaderboards branch.
branding:
  icon: flag  
  color: black
inputs:
  token:
    description: Github token to open a PR
    required: true
runs:
  using: composite 
  steps:
    - name: Checking out the repository
      uses: actions/checkout@v3
      with:
        path: ros_ws/src/ros2_kart_racing_competition
        ref: competition
        fetch-depth: 0
    - name: Copying dependencies to /tmp...
      run: bash -c "cp ros_ws/src/ros2_kart_racing_competition/dependencies.repos /tmp/"
      shell: bash
    - name: Setting up ROS
      uses: ros-tooling/setup-ros@v0.4
      with:
        required-ros-distributions: humble
    - name: Making sure the package builds (colcon build)
      uses: ros-tooling/action-ros-ci@v0.2
      with:
        target-ros2-distro: humble
        skip-tests: true
        colcon-defaults: |
          {
            "build": {
              "symlink-install": true
            }
          }
        vcs-repo-file-url: /tmp/dependencies.repos
    - name: Downloading gh
      run: sudo DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends --quiet --yes gh
      shell: bash
    - name: Forking the ros2_kart_racing repository (for leaderboards)
      env:
        GH_TOKEN: "${{ inputs.token }}"
      run: |
        gh repo fork gstavrinos/ros2_kart_racing --clone=true -- --branch leaderboards
      shell: bash
    - name: "Running the simulation on track: kartland"
      run: bash -c "source /opt/ros/humble/setup.sh && source ros_ws/install/setup.bash && ros2 launch kart_simulation kart_kartland_simulation.launch.py competition_mode:=true gui:=false &"
      shell: bash
    # - name: Running the competition judge
      # run: bash -c "source /opt/ros/humble/setup.sh && source ros_ws/install/setup.bash && python3 ${GITHUB_ACTION_PATH}/competition_judge.py ${{ github.triggering_actor }}"
      # shell: bash
    - name: Dummy leaderboards file for testing
      run: bash -c "echo $(date) >> ros2_kart_racing/kartland.md"
      shell: bash
    - name: Adding record on leaderboards
      env:
        GH_TOKEN: "${{ inputs.token }}"
        MESSAGE: "${{ github.triggering_actor }}: new kartland record!"
      run: |
        export NOW="$( date -u '+%Y-%m-%d_%H-%M-%S' )"
        export DESTINATION_BRANCH=${{ github.triggering_actor }}"-pb-"${NOW}
        cd ros2_kart_racing
        git checkout -b "${DESTINATION_BRANCH}"
        git add kartland.md
        git config --replace-all user.name "${{ github.triggering_actor }}"
        git config --replace-all user.email "${{ github.triggering_actor }}@users.noreply.github.com"
        git commit -m "$MESSAGE"
        git push origin ${DESTINATION_BRANCH}
        gh pr create -r gstavrinos -a gstavrinos -B leaderboards -t "$MESSAGE" -b "At $NOW in ${{ github.repositoryUrl }}, commit: ${{ github.sha }}, triggered by ${{ github.workflow }} with a ${{ github.event_name }} event from the ${{ github.action }} action."
      shell: bash
