name: ROS2 Kart Racing Competition
author: George Stavrinos
description: The action that is used by the ros2_kart_racing competition package to add users to the leaderboards branch.
branding:
  icon: flag  
  color: black

runs:
  using: composite 
  steps:
    - name: Checking out the repository
      uses: actions/checkout@v3
      with:
        path: ros_ws/src/ros2_kart_racing_competition
        ref: competition
        fetch-depth: 0
    - name: Copying dependencies to /tmp...
      run: bash -c "cp ros_ws/src/ros2_kart_racing_competition/dependencies.repos /tmp/"
      shell: bash
    - name: Checking out the ros2_kart_racing repository (leaderboards)
      uses: actions/checkout@v3
      with:
        repository: gstavrinos/ros2_kart_racing
        path: ros2_kart_racing
        ref: leaderboards
        fetch-depth: 0
    - name: Setting up ROS
      uses: ros-tooling/setup-ros@v0.4
      with:
        required-ros-distributions: humble
    - name: Making sure the package builds (colcon build)
      uses: ros-tooling/action-ros-ci@v0.2
      with:
        target-ros2-distro: humble
        skip-tests: true
        colcon-defaults: |
          {
            "build": {
              "symlink-install": true
            }
          }
        vcs-repo-file-url: /tmp/dependencies.repos
    - name: "Running the simulation on track: kartland"
      run: bash -c "source /opt/ros/humble/setup.sh && source ros_ws/install/setup.bash && ros2 launch kart_simulation kart_kartland_simulation.launch.py competition_mode:=true gui:=false &"
      shell: bash
    # - name: Running the competition judge
      # run: bash -c "source /opt/ros/humble/setup.sh && source ros_ws/install/setup.bash && python3 ${GITHUB_ACTION_PATH}/competition_judge.py ${{ github.triggering_actor }}"
      # shell: bash
    - name: Dummy leaderboards file for testing
      run: bash -c "echo $(date) >> ros2_kart_racing/kartland.md"
      shell: bash
    - name: Adding record on leaderboards
      env:
        TRACK: kartland
        FILE_TO_COMMIT: ${TRACK}.md
        DESTINATION_BRANCH: leaderboards
      run: |
        cd ros2_kart_racing
        export NOW=$( date -u '+%Y-%m-%d_%H:%M:%S' )
        export MESSAGE="${{ github.triggering_actor }}: new $TRACK record at $NOW"
        git checkout -b "${{ github.triggering_actor }}-leaderboards-$NOW"
        git add $FILE_TO_COMMIT
        git commit -m "$MESSAGE"
        gh pr create -r gstavrinos -a gstavrinos -f
      shell: bash
